spring.application.name=product-service
spring.data.mongodb.uri=mongodb://localhost:27017/product-service
server.port=8083
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#old boot 2.X
#spring.zipkin.base-url= http://localhost:9411/zipkin
#spring.sleuth.sampler.probability=1.0
#old boot 3.X
# Sample all requests (like Sleuth probability=1.0)
management.tracing.sampling.probability=1.0

# Send traces to Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans