spring.application.name=discovery-server
eureka.client.service-url.defaultZone=http://eureka-user:eureka-pass@localhost:8761/eureka

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=8761

eureka.username=${EUREKA_USERNAME:admin}
eureka.password=${EUREKA_PASSWORD:admin}

#old boot 2.X
#spring.zipkin.base-url= http://localhost:9411/zipkin
#spring.sleuth.sampler.probability=1.0
#old boot 3.X
# Sample all requests (like Sleuth probability=1.0)
management.tracing.sampling.probability=1.0

# Send traces to Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans